### ISSUE TITLE
Tie in redis support on some level

### ISSUE THREAD

**Issue by Scarly-Crow** [Scarly-Crow/lamia#2]
This would be nice to have, but at the moment, there's no specific approach that I'm fond of.

**Comment by cbondurant** [comment]
I am currently trying to grasp what the best use-case to assume when building redis into the codebase. 
My main two thoughts are 
1) we could have very small wrappers over one of the few asyncio redis codebases ([aioredis](https://github.com/aio-libs/aioredis) looks like a good choice), and allow it to be used practically as a catch-all scratch pad wherever it could be useful. Pretty much just ensuring the connection singleton is safe.
2) a more complex wrapper that works to prevent mangling/unwanted reads between different concurrent requests that have somehow asked for the same key without properly sharing access. (this could be as easy as just tacking something consistent to the requests(account id, session id, etc),  such that they can only be grabbed if you have the right thing to tack onto them) 

1 is clearly easier but I think 2 has a better chance of working for us, because it would be a very simple safety measure to prevent unintended data clobber, or data read to the wrong users.

Looking around also points to the publish/subscribe pattern? which sounds like something we would end up using a ton based on just how AP works as a whole.

**Comment by Scarly-Cat** [comment]
Good post! I think that a strong execution of (1) would be sufficient for our needs. Every object that we're likely to cache will having a unique identifier associated with it, so it isn't likely that we will have any unwanted data clobbering issues.

Basically, the code that handles redis will need to be reliable but also minimal, because the code that uses it will have some logic around it. Now, down the line, we may centralize some of that logic. In this case, (1) would evolve into (2). However, I prefer the gradual evolution to the more heavily engineered version at this point. 

Let's start with the basics and then put them into play to see where things end up.

**Comment by Scarly-Cat** [comment]
Hmmm. Redis pubsub seems redundant with the pubsub functionality that we'll already by building up with celery and postgresql. (Huh, is Celery compatible with these async redis wraps.... I haven't checked yet. XD)
